[feat] scroll scale map
xerxes228007/Hex pull request #9
Opened 2024-04-15 11:51 UTC by xerxes228007

scaleUp scaleDown map, units and structures

2024-04-15 11:54 UTC, DOXECEES commented on src/mainwindow.cpp
> +            if(map[i][j].isHereStructere()){
В чем смысл if-a

2024-04-15 11:56 UTC, DOXECEES commented on src/mainwindow.cpp
> +            if(mapPolygons[i][j].containsPoint(QPointF(mapFromGlobal(QCursor::pos()).x(), mapFromGlobal(QCursor::pos()).y()),Qt::FillRule::OddEvenFill)){
Нечитаемо

2024-04-15 11:57 UTC, DOXECEES commented on src/mainwindow.cpp
> +            polygon[i].setY(polygon[i].y()*1.1);
что за 1.1?

2024-04-15 11:59 UTC, DOXECEES commented on src/mainwindow.cpp
>                  if(map[i][j].isHereUnit()&&firstCkick.x()==-1 && firstCkick.y()==-1){
мб firstClick?
-1 мб стоит как-либо назвать(Типа NO_CLICK)

2024-04-15 12:00 UTC, DOXECEES commented on src/mainwindow.cpp
> +        scale = 1.10;
Между 1.1 и 1.10 нет разницы
+ магические числа.

2024-04-15 12:00 UTC, DOXECEES requested changes
См. комментарии

2024-04-15 12:09 UTC, xerxes228007 commented on src/mainwindow.cpp
> +            if(map[i][j].isHereStructere()){
ТАК НАДО

2024-04-15 12:09 UTC, xerxes228007 commented on src/mainwindow.cpp
> +            if(mapPolygons[i][j].containsPoint(QPointF(mapFromGlobal(QCursor::pos()).x(), mapFromGlobal(QCursor::pos()).y()),Qt::FillRule::OddEvenFill)){
ну тут ничего не поделать

2024-04-15 12:09 UTC, xerxes228007 commented on src/mainwindow.cpp
> +            polygon[i].setY(polygon[i].y()*1.1);
исправлю

2024-04-15 12:09 UTC, xerxes228007 commented on src/mainwindow.cpp
>                  if(map[i][j].isHereUnit()&&firstCkick.x()==-1 && firstCkick.y()==-1){
исправлю

2024-04-15 12:09 UTC, xskerty commented on src/mainwindow.cpp
> +        scale = 1.10;
исправлю

2024-04-15 12:11 UTC, DOXECEES commented on src/mainwindow.cpp
> +            if(mapPolygons[i][j].containsPoint(QPointF(mapFromGlobal(QCursor::pos()).x(), mapFromGlobal(QCursor::pos()).y()),Qt::FillRule::OddEvenFill)){
mapFromGlobal(QCursor::pos()).x(), mapFromGlobal(QCursor::pos()).y()) - Вынести в отдельную переменную

2024-04-16 09:11 UTC, DOXECEES approved these changes
approve

2024-04-16 09:12 UTC, merged